import { randomUUID } from "node:crypto"
import { existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs"
import path from "node:path"

/**
 * Durable store for generated media bytes.
 *
 * Every image provider in this app returns either a `data:` URI or a remote URL
 * that expires. Previously the chat card carried that whole `data:` URI in React
 * state, which meant:
 *
 *   - the multi-megabyte string was written into localStorage with the rest of
 *     the dashboard state, blowing the ~5MB quota and silently killing every
 *     later save (so a refresh restored a snapshot from *before* the image);
 *   - the only durable copy lived in the browser's IndexedDB, so the result was
 *     invisible on any other device and disappeared when storage was cleared.
 *
 * Generated bytes are now written here first and handed to the client as a short,
 * stable `/api/media/asset/<id>` URL that survives reloads and works everywhere.
 */

// Ultra 16K masters can be around 30MB. The previous 24MB ceiling meant a
// successful high-quality render could silently fall back to the provider's
// lower-resolution source on hosts without cloud storage. 64MB keeps the exact
// requested master while the global store budget below still limits total disk.
const MAX_ASSET_BYTES = 64 * 1024 * 1024
const MAX_STORE_BYTES = 2 * 1024 * 1024 * 1024
const MAX_STORE_ENTRIES = 4000
const MAX_ASSET_AGE_MS = 30 * 24 * 60 * 60 * 1000

const EXTENSIONS: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/jpg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
  "image/svg+xml": "svg",
  "video/mp4": "mp4",
  "video/webm": "webm",
}

export type StoredMediaAsset = {
  id: string
  url: string
  mime: string
  bytes: number
}

export type StoredMediaAssetFile = {
  buffer: Buffer
  mime: string
  bytes: number
}

type IndexEntry = { id: string; mime: string; bytes: number; at: number }

export function mediaAssetDirectory() {
  // Runtime-only data: never let build tracing bundle user generations.
  return path.resolve(/* turbopackIgnore: true */ process.env.MALIK_MEDIA_DATA_DIR || path.join(process.cwd(), ".data", "malik-media"))
}

function assetFile(id: string) {
  return path.join(mediaAssetDirectory(), `${id}.bin`)
}

function metaFile(id: string) {
  return path.join(mediaAssetDirectory(), `${id}.json`)
}

function indexFile() {
  return path.join(mediaAssetDirectory(), "index.json")
}

/** Ids are generated here, so anything that is not a plain uuid is a traversal attempt. */
export function isValidMediaAssetId(value: unknown): value is string {
  return typeof value === "string" && /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(value)
}

export function mediaAssetUrl(id: string) {
  return `/api/media/asset/${id}`
}

function normalizeMime(value: string | undefined, fallback = "image/jpeg") {
  const mime = String(value || "").split(";")[0].trim().toLowerCase()
  return EXTENSIONS[mime] ? mime : fallback
}

export function mediaAssetExtension(mime: string) {
  return EXTENSIONS[normalizeMime(mime)] || "bin"
}

/** Parses `data:image/png;base64,...` into raw bytes. Returns null for anything else. */
export function decodeDataUrl(value: string): { buffer: Buffer; mime: string } | null {
  // Providers are allowed to add parameters before `;base64` (for example
  // `data:image/jpeg;charset=utf-8;base64,...`). The old parser rejected that
  // perfectly valid form, so a megabyte-long URI leaked into React/IndexedDB
  // instead of becoming a short durable asset URL.
  const match = /^data:([^;,]+)((?:;[^,]*)*),([\s\S]*)$/i.exec(String(value || ""))
  if (!match) return null
  const mime = normalizeMime(match[1])
  try {
    const isBase64 = /(?:^|;)base64(?:;|$)/i.test(match[2] || "")
    const buffer = isBase64
      ? Buffer.from(match[3], "base64")
      : Buffer.from(decodeURIComponent(match[3]), "utf8")
    return buffer.length ? { buffer, mime } : null
  } catch {
    return null
  }
}

/**
 * Retention is driven by a small append-style index rather than by scanning the
 * directory. That keeps housekeeping O(1) per generation, and it keeps the
 * bundler's file tracer out of a dynamic `readdir`/`stat` walk, which otherwise
 * makes it trace the entire project into the build output.
 */
function readIndex(): IndexEntry[] {
  try {
    const file = indexFile()
    if (!existsSync(/* turbopackIgnore: true */ file)) return []
    const parsed = JSON.parse(readFileSync(/* turbopackIgnore: true */ file, "utf8"))
    if (!Array.isArray(parsed)) return []
    return parsed
      .filter((entry) => isValidMediaAssetId(entry?.id) && Number.isFinite(Number(entry?.at)))
      .map((entry) => ({
        id: String(entry.id),
        mime: normalizeMime(entry.mime),
        bytes: Math.max(0, Number(entry.bytes) || 0),
        at: Number(entry.at),
      }))
  } catch {
    return []
  }
}

function writeIndex(entries: IndexEntry[]) {
  try {
    const file = indexFile()
    const temporary = `${file}.${process.pid}.tmp`
    writeFileSync(temporary, JSON.stringify(entries), { mode: 0o600 })
    renameSync(temporary, file)
  } catch {
    /* an unwritable index only means retention is deferred */
  }
}

function removeAsset(id: string) {
  try { unlinkSync(assetFile(id)) } catch {}
  try { unlinkSync(metaFile(id)) } catch {}
}

/**
 * Drops assets past the retention window, then the oldest ones until the store
 * fits its budgets. Housekeeping must never break a generation, so every error
 * here is swallowed on purpose.
 */
function pruneIndex(entries: IndexEntry[]): IndexEntry[] {
  const now = Date.now()
  let live: IndexEntry[] = []

  for (const entry of entries.sort((a, b) => a.at - b.at)) {
    if (now - entry.at > MAX_ASSET_AGE_MS) removeAsset(entry.id)
    else live.push(entry)
  }

  let total = live.reduce((sum, entry) => sum + entry.bytes, 0)
  while (live.length && (total > MAX_STORE_BYTES || live.length > MAX_STORE_ENTRIES)) {
    const oldest = live.shift()!
    removeAsset(oldest.id)
    total -= oldest.bytes
  }

  return live
}

function prepareAssetInput(input: {
  buffer?: Buffer
  dataUrl?: string
  mime?: string
}) {
  let buffer = input.buffer
  let mime = normalizeMime(input.mime)

  if (!buffer && input.dataUrl) {
    const decoded = decodeDataUrl(input.dataUrl)
    if (!decoded) return null
    buffer = decoded.buffer
    mime = input.mime ? normalizeMime(input.mime) : decoded.mime
  }

  if (!buffer?.length || buffer.length > MAX_ASSET_BYTES) return null
  return { buffer, mime }
}

/**
 * Writes bytes to the store and returns the stable public URL, or null when the
 * filesystem is unavailable (read-only serverless FS, full disk). Callers must
 * treat null as "keep using the inline data URL" rather than as a failure.
 */
export function saveMediaAsset(input: {
  buffer?: Buffer
  dataUrl?: string
  mime?: string
}): StoredMediaAsset | null {
  const prepared = prepareAssetInput(input)
  if (!prepared) return null
  const { buffer, mime } = prepared

  try {
    const directory = mediaAssetDirectory()
    mkdirSync(directory, { recursive: true, mode: 0o700 })

    const id = randomUUID()
    const target = assetFile(id)
    const temporary = `${target}.${process.pid}.tmp`

    // Write to a temp file first: a reader must never observe a half-written asset.
    writeFileSync(temporary, buffer, { mode: 0o600 })
    renameSync(temporary, target)

    const createdAt = Date.now()
    writeFileSync(metaFile(id), JSON.stringify({ id, mime, bytes: buffer.length, createdAt }), { mode: 0o600 })

    try {
      writeIndex(pruneIndex([...readIndex(), { id, mime, bytes: buffer.length, at: createdAt }]))
    } catch {
      /* retention is best effort; the asset itself is already safe on disk */
    }

    return { id, url: mediaAssetUrl(id), mime, bytes: buffer.length }
  } catch {
    return null
  }
}

/**
 * Async persistence path for large generated masters. `writeFileSync()` on a
 * 15-30MB 8K/16K image pauses the Node event loop while the file hits disk, so
 * every request on the same Next.js process can feel frozen right after image
 * generation. The bytes and resulting URL are identical; only I/O scheduling is
 * different. Small index maintenance is deferred after the asset is already safe.
 */
export async function saveMediaAssetAsync(input: {
  buffer?: Buffer
  dataUrl?: string
  mime?: string
}): Promise<StoredMediaAsset | null> {
  const prepared = prepareAssetInput(input)
  if (!prepared) return null
  const { buffer, mime } = prepared

  const id = randomUUID()
  const directory = mediaAssetDirectory()
  const target = assetFile(id)
  const temporary = `${target}.${process.pid}.${Date.now()}.tmp`

  try {
    const fs = await import("node:fs/promises")
    await fs.mkdir(directory, { recursive: true, mode: 0o700 })
    await fs.writeFile(temporary, buffer, { mode: 0o600 })
    await fs.rename(temporary, target)

    const createdAt = Date.now()
    await fs.writeFile(metaFile(id), JSON.stringify({ id, mime, bytes: buffer.length, createdAt }), { mode: 0o600 })

    // Retention bookkeeping is tiny compared with the master write and need not
    // sit on the response critical path.
    setImmediate(() => {
      try {
        writeIndex(pruneIndex([...readIndex(), { id, mime, bytes: buffer.length, at: createdAt }]))
      } catch {
        /* retention is best effort */
      }
    })

    return { id, url: mediaAssetUrl(id), mime, bytes: buffer.length }
  } catch {
    try {
      const fs = await import("node:fs/promises")
      await fs.unlink(temporary).catch(() => {})
    } catch {}
    return null
  }
}

export function readMediaAsset(id: string): StoredMediaAssetFile | null {
  if (!isValidMediaAssetId(id)) return null
  try {
    const file = assetFile(id)
    if (!existsSync(/* turbopackIgnore: true */ file)) return null
    const buffer = readFileSync(/* turbopackIgnore: true */ file)
    let mime = "image/jpeg"
    try {
      const meta = JSON.parse(readFileSync(/* turbopackIgnore: true */ metaFile(id), "utf8"))
      mime = normalizeMime(meta?.mime)
    } catch {
      /* meta is optional; the bytes are what matter */
    }
    return { buffer, mime, bytes: buffer.length }
  } catch {
    return null
  }
}
