import type { BusinessSection } from "./types"

export const BUSINESS_SECTIONS: BusinessSection[] = [
  {
    id: "business-doctor",
    title: "Business Doctor",
    titleRu: "Business Doctor",
    subtitle: "Diagnose, fix, optimize the business",
    subtitleRu: "Лечит бизнес: диагноз, план, оптимизация",
    accent: "cyan",
  },
  {
    id: "sales-booster",
    title: "Sales Booster",
    titleRu: "Sales Booster",
    subtitle: "Revenue, offers, objections, scripts",
    subtitleRu: "Поднимает продажи и конверсию",
    accent: "emerald",
  },
  {
    id: "marketing-war-room",
    title: "Marketing War Room",
    titleRu: "Marketing War Room",
    subtitle: "Ads, content, brand, competitors",
    subtitleRu: "Делает продвижение и контент",
    accent: "violet",
  },
  {
    id: "founder-commander",
    title: "Founder Commander",
    titleRu: "Founder Commander",
    subtitle: "Daily plan, team tasks, solo ops",
    subtitleRu: "Управляет задачами founder",
    accent: "amber",
  },
  {
    id: "investor-mode",
    title: "Investor Mode",
    titleRu: "Investor Mode",
    subtitle: "Pitch prep, Q&A, battle simulator",
    subtitleRu: "Готовит к инвесторам",
    accent: "rose",
  },
  {
    id: "crisis-mode",
    title: "Crisis Mode",
    titleRu: "Crisis Mode",
    subtitle: "24h survival and reputation defense",
    subtitleRu: "Спасает при проблемах",
    accent: "blue",
  },
  {
    id: "launch-engine",
    title: "Launch Engine",
    titleRu: "Launch Engine",
    subtitle: "Full product launch domination pack",
    subtitleRu: "Доводит до релиза",
    accent: "cyan",
  },
  {
    id: "newsroom-desk",
    title: "Newsroom Desk",
    titleRu: "Редакция",
    subtitle: "Articles, breaking news, fact-check, interviews",
    subtitleRu: "Новости, статьи, фактчек, интервью — под публикацию",
    accent: "blue",
  },
  {
    id: "social-media-desk",
    title: "Social Media Desk",
    titleRu: "Соцсети / SMM",
    subtitle: "Instagram, Telegram, TikTok/Reels cuts",
    subtitleRu: "Посты и нарезки для соцсетей СМИ",
    accent: "violet",
  },
  {
    id: "broadcast-desk",
    title: "Broadcast Desk",
    titleRu: "Эфир / ТВ",
    subtitle: "TV scripts, teleprompter, storyboards",
    subtitleRu: "Сценарии, телесуфлёр, раскадровки сюжетов",
    accent: "rose",
  },
  {
    id: "media-language",
    title: "Language Desk",
    titleRu: "Язык / Перевод",
    subtitle: "KZ↔RU↔EN, Kazakh editing, rewrite",
    subtitleRu: "Перевод KZ↔RU↔EN, редактура казахского, рерайт",
    accent: "emerald",
  },
  {
    id: "demo-day",
    title: "Digital Bridge 2026",
    titleRu: "Digital Bridge 2026",
    subtitle: "Pitch deck, demo, jury simulator, winning narrative",
    subtitleRu: "Победный набор: питч, demo, симулятор жюри, нарратив №1",
    accent: "amber",
  },
]
