from __future__ import annotations

import json
import re
import time
import uuid
from typing import Any, Dict

def _slug(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9а-яА-ЯёЁ]+", "-", value.lower()).strip("-")
    return cleaned[:48] or "malik-project"

def _title(prompt: str) -> str:
    prompt = " ".join((prompt or "").split())
    return prompt[:72] or "MALIK AI Project"

def build_project(prompt: str, provider: str = "local-project-builder") -> Dict[str, Any]:
    title = _title(prompt)
    slug = _slug(title)
    project_id = f"project_{uuid.uuid4().hex[:12]}"

    page = f'''export default function Page() {{
  return (
    <main className="min-h-screen bg-[#030305] text-white">
      <section className="mx-auto flex min-h-screen max-w-6xl flex-col justify-center px-6 py-16">
        <p className="w-fit rounded-full border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm font-black text-cyan-200">
          MALIK AI Project Builder
        </p>
        <h1 className="mt-8 text-4xl font-black tracking-tight sm:text-6xl">{title}</h1>
        <p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-300">{prompt}</p>
        <div className="mt-10 grid gap-4 md:grid-cols-3">
          {{["Plan", "Build", "Deploy"].map((item) => (
            <div key={{item}} className="rounded-3xl border border-white/10 bg-white/[0.05] p-6">
              <h2 className="text-2xl font-black">{{item}}</h2>
              <p className="mt-3 text-zinc-400">Production-ready module generated by MALIK AI.</p>
            </div>
          ))}}
        </div>
      </section>
    </main>
  )
}}
'''

    files = [
        {
            "path": "package.json",
            "language": "json",
            "content": json.dumps({
                "name": slug,
                "version": "1.0.0",
                "private": True,
                "scripts": {"dev": "next dev", "build": "next build", "start": "next start", "lint": "eslint ."},
                "dependencies": {"next": "latest", "react": "latest", "react-dom": "latest", "lucide-react": "latest"},
                "devDependencies": {"typescript": "latest", "tailwindcss": "latest", "eslint": "latest"}
            }, ensure_ascii=False, indent=2),
        },
        {"path": "app/page.tsx", "language": "tsx", "content": page},
        {
            "path": "app/layout.tsx",
            "language": "tsx",
            "content": '''import "./globals.css"

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body>{children}</body>
    </html>
  )
}
''',
        },
        {"path": "app/globals.css", "language": "css", "content": "@tailwind base;\n@tailwind components;\n@tailwind utilities;\nbody{margin:0;background:#030305;}\n"},
        {
            "path": "README.md",
            "language": "markdown",
            "content": f"# {title}\n\nGenerated by MALIK AI Project Builder.\n\n## Commands\n\n```bash\nnpm install\nnpm run dev\nnpm run build\n```\n",
        },
    ]

    return {
        "projectId": project_id,
        "title": title,
        "description": "Generated project plan, file tree, code files and setup commands.",
        "status": "completed",
        "provider": provider,
        "model": "safe-project-fallback",
        "plan": [
            "Analyze product idea",
            "Create architecture",
            "Generate file tree",
            "Write starter code",
            "Return setup commands",
        ],
        "structure": [f["path"] for f in files],
        "files": files,
        "commands": ["npm install", "npm run dev", "npm run build"],
        "createdAt": int(time.time()),
    }
