import { applyFreeModeRequest } from "@/lib/ai/free-mode"
import { routeAI } from "@/lib/ai/router"
import { generateImageWithRouter, generateVideoWithRouter } from "@/lib/ai/media-router"
import { publicEngineForProvider, publicErrorMessage } from "@/lib/brand-provider-map"
import { checkRateLimit } from "@/lib/ai/rate-limit"
import { incrementUsage } from "@/lib/ai/usage"
import { createAIJob, updateAIJob, type AIJobInput } from "@/lib/ai/jobs"
import { resolveRequestEntitlement } from "@/lib/server/request-entitlement"

type GenerationBody = {
  kind?: string
  prompt?: string
  message?: string
  style?: string
  format?: string
  aspectRatio?: string
  duration?: number
  userEmail?: string
}

const SUPPORTED_KINDS = new Set(["photo", "image", "video", "code", "website", "landing", "dashboard", "document", "presentation", "template"])

function escapeHtml(value: string) {
  return value.replace(/[<>&"]/g, (char) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" })[char] || char)
}

function artifactId(kind: string) {
  return `malik_${kind}_${Date.now()}`
}

function websiteArtifact(prompt: string, kind: string) {
  const title = escapeHtml(prompt || "Malik AI generated product")
  return `<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-[#020308] text-white"><main class="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_18%_12%,rgba(34,211,238,.16),transparent_32%),radial-gradient(circle_at_82%_22%,rgba(139,92,246,.22),transparent_36%),#020308]"><section class="mx-auto max-w-6xl px-8 py-20"><p class="font-black text-cyan-300">Generated by Malik AI</p><h1 class="mt-5 max-w-5xl text-6xl font-black">${title}</h1><p class="mt-5 max-w-2xl text-slate-300">Production-ready ${escapeHtml(kind)} starter.</p><button class="mt-8 rounded-2xl bg-white px-7 py-4 font-black text-black">Launch</button></section></main></body></html>`
}

function codeArtifact(prompt: string) {
  return `"use client"

export default function MalikGeneratedFeature() {
  return (
    <main className="min-h-screen bg-slate-950 p-8 text-white">
      <section className="mx-auto max-w-5xl rounded-3xl border border-cyan-400/20 bg-white/5 p-8">
        <p className="text-cyan-300">Malik AI Code Generator</p>
        <h1 className="mt-4 text-4xl font-black">${escapeHtml(prompt || "Generated feature")}</h1>
      </section>
    </main>
  )
}
`
}

function imageFallbackUrl(prompt: string) {
  const safe = escapeHtml((prompt || "Malik AI image").slice(0, 120))
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1344" height="768"><defs><radialGradient id="g" cx="28%" cy="18%" r="90%"><stop stop-color="#7c3aed"/><stop offset=".45" stop-color="#0f172a"/><stop offset="1" stop-color="#020617"/></radialGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="1010" cy="160" r="210" fill="#22d3ee" opacity=".18"/><text x="96" y="150" fill="#fff" font-family="Arial" font-size="46" font-weight="900">Malik Vision Demo</text><foreignObject x="96" y="530" width="1100" height="130"><div xmlns="http://www.w3.org/1999/xhtml" style="color:white;font-family:Arial;font-size:34px;font-weight:900">${safe}</div></foreignObject></svg>`
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
}

function videoFallbackPreviewUrl(prompt: string): string {
  const safe = escapeHtml((prompt || "Malik AI video").slice(0, 100))
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><defs><linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" style="stop-color:#7c3aed;stop-opacity:1" /><stop offset="50%" style="stop-color:#22d3ee;stop-opacity:.3" /><stop offset="100%" style="stop-color:#1a1a2e;stop-opacity:1" /></linearGradient><pattern id="grid" width="60" height="60" patternUnits="userSpaceOnUse"><path d="M 60 0 L 0 0 0 60" fill="none" stroke="#22d3ee" stroke-width="0.5" opacity="0.3"/></pattern></defs><rect width="100%" height="100%" fill="url(#grad)"/><rect width="100%" height="100%" fill="url(#grid)"/><circle cx="640" cy="180" r="120" fill="#22d3ee" opacity="0.15"/><circle cx="200" cy="600" r="150" fill="#7c3aed" opacity="0.1"/><rect x="100" y="280" width="1080" height="200" rx="20" fill="#020308" opacity="0.8" stroke="#22d3ee" stroke-width="2"/><text x="640" y="340" text-anchor="middle" fill="#22d3ee" font-family="Arial" font-size="28" font-weight="900">MALIK AI Video Storyboard</text><text x="640" y="390" text-anchor="middle" fill="#cbd5e1" font-family="Arial" font-size="18">${safe}</text><text x="640" y="450" text-anchor="middle" fill="#64748b" font-family="Arial" font-size="14">Live rendering preparing...</text></svg>`
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
}

function textPrompt(kind: string, prompt: string) {
  if (kind === "code") return `Create a usable code artifact for this request. Return the complete code, not a placeholder.\n\n${prompt}`
  if (kind === "document") return `Create a polished document outline with usable content for this request.\n\n${prompt}`
  if (kind === "presentation") return `Create a polished presentation structure with slide titles and content for this request.\n\n${prompt}`
  return `Create a complete standalone HTML artifact for a ${kind}. Return one usable HTML document with responsive styling.\n\n${prompt}`
}

function responseArtifact(kind: string, prompt: string, code?: string, url?: string) {
  return {
    id: artifactId(kind),
    title: prompt.slice(0, 90) || `Malik AI ${kind}`,
    kind,
    code,
    html: kind === "code" ? undefined : code,
    url,
    createdAt: new Date().toISOString(),
  }
}

function outputUrl(output: unknown) {
  if (!output || typeof output !== "object") return ""
  const value = output as Record<string, unknown>
  return String(value.resultUrl || value.url || value.imageUrl || value.videoUrl || "")
}

function outputRecord(output: unknown) {
  return output && typeof output === "object" ? output as Record<string, unknown> : {}
}

const VIDEO_ASPECT_RATIOS: Array<NonNullable<AIJobInput["aspectRatio"]>> = ["1:1", "16:9", "9:16", "4:3", "3:4"]

function videoAspectRatio(value: unknown): NonNullable<AIJobInput["aspectRatio"]> {
  const normalized = String(value || "16:9")
  return VIDEO_ASPECT_RATIOS.includes(normalized as NonNullable<AIJobInput["aspectRatio"]>)
    ? normalized as NonNullable<AIJobInput["aspectRatio"]>
    : "16:9"
}

function videoDuration(value: unknown): NonNullable<AIJobInput["duration"]> {
  const numeric = Number(value || 5)
  if (numeric <= 5) return 5
  if (numeric <= 8) return 8
  if (numeric <= 10) return 10
  return 12
}

function localVideoStatusUrl(jobId: string) {
  return `/api/ai/video/status?jobId=${encodeURIComponent(jobId)}`
}

export async function handleGenerateRequest(request: Request, routeKind?: string) {
  const body = (await request.json().catch(() => ({}))) as GenerationBody
  const entitlement = await resolveRequestEntitlement(request)
  const kind = String(routeKind || body.kind || "code").toLowerCase()
  const prompt = String(body.prompt || body.message || "").trim()
  const requestedProvider = "auto"

  if (!SUPPORTED_KINDS.has(kind)) {
    return Response.json({ ok: false, kind, status: "unsupported", error: "unsupported_kind", message: `Unsupported generation kind: ${kind}` }, { status: 400 })
  }

  if (!prompt) {
    return Response.json({ ok: false, kind, status: "invalid", error: "prompt_required", message: "Prompt is required." }, { status: 400 })
  }

  if (kind === "photo" || kind === "image") {
    const rate = checkRateLimit({ userId: entitlement.userId, plan: entitlement.plan, task: "image" })
    if (!rate.ok) {
      const url = imageFallbackUrl(prompt)
      incrementUsage(entitlement.userId, entitlement.plan, "image")
      return Response.json({ ok: true, kind, engine: publicEngineForProvider("demo-fallback", kind).title, fallbackUsed: true, status: "demo-ready", url, imageUrl: url, fallback: true, artifact: responseArtifact(kind, prompt, undefined, url), message: "Limit reached. Demo preview ready. Upgrade for more daily generations.", publicError: rate.message })
    }
    try {
      const result = await generateImageWithRouter({
        prompt,
        task: "image",
        provider: requestedProvider,
        userId: entitlement.userId,
        userEmail: entitlement.userId,
        plan: entitlement.plan,
        signal: request.signal,
        metadata: {
          requestedProvider,
          style: body.style,
          format: body.format,
          aspectRatio: body.aspectRatio,
        },
      })
      const url = outputUrl(result.output)
      if (!url) throw new Error("Image provider returned no image URL.")
      incrementUsage(entitlement.userId, entitlement.plan, "image")
      return Response.json({ ok: true, kind, engine: publicEngineForProvider(result.provider, kind).title, fallbackUsed: false, status: "ready", url, imageUrl: url, artifact: responseArtifact(kind, prompt, undefined, url), message: "Image generated." })
    } catch (error) {
      const url = imageFallbackUrl(prompt)
      incrementUsage(entitlement.userId, entitlement.plan, "image")
      return Response.json({ ok: true, kind, engine: publicEngineForProvider("demo-fallback", kind).title, fallbackUsed: true, status: "demo-ready", url, imageUrl: url, fallback: true, artifact: responseArtifact(kind, prompt, undefined, url), message: "Demo image preview ready. Live image generation will work after server provider keys are configured.", publicError: publicErrorMessage(error) })
    }
  }

  if (kind === "video") {
    const rate = checkRateLimit({ userId: entitlement.userId, plan: entitlement.plan, task: "video" })
    if (!rate.ok) {
      const previewUrl = videoFallbackPreviewUrl(prompt)
      incrementUsage(entitlement.userId, entitlement.plan, "video")
      return Response.json({ ok: true, kind, engine: publicEngineForProvider("demo-fallback", kind).title, fallbackUsed: true, status: "storyboard-ready", fallback: true, url: previewUrl, videoUrl: previewUrl, posterUrl: previewUrl, previewUrl: previewUrl, artifact: responseArtifact(kind, prompt, undefined, previewUrl), message: "Limit reached. Demo storyboard ready. Upgrade for more daily generations.", publicError: rate.message })
    }
    const videoMetadata = {
      requestedProvider,
      aspectRatio: videoAspectRatio(body.aspectRatio),
      duration: videoDuration(body.duration),
      style: body.style,
      format: body.format,
    }
    const localJob = createAIJob("video", {
      prompt,
      userId: entitlement.userId,
      userEmail: entitlement.userId,
      provider: requestedProvider,
      aspectRatio: videoMetadata.aspectRatio,
      duration: videoMetadata.duration,
      metadata: videoMetadata,
    })
    try {
      const result = await generateVideoWithRouter({
        prompt,
        task: "video",
        provider: requestedProvider,
        userId: entitlement.userId,
        userEmail: entitlement.userId,
        plan: entitlement.plan,
        signal: request.signal,
        metadata: videoMetadata,
      })
      const url = outputUrl(result.output)
      const output = outputRecord(result.output)
      const jobId = String(output.jobId || output.id || "")
      const status = String(output.status || (url ? "ready" : "queued"))
      if (!url && !jobId) throw new Error("Video provider returned no URL or job id.")
      updateAIJob(localJob.id, {
        status: url ? "completed" : "processing",
        provider: result.provider,
        model: result.model,
        output: {
          resultUrl: url || undefined,
          provider: result.provider,
          model: result.model,
          raw: {
            ...output,
            provider: result.provider,
            model: result.model,
          },
        },
      })
      incrementUsage(entitlement.userId, entitlement.plan, "video")
      return Response.json({
        ok: true,
        kind,
        engine: publicEngineForProvider(result.provider, kind).title,
        fallbackUsed: false,
        status,
        url: url || undefined,
        videoUrl: url || undefined,
        jobId: localJob.id,
        statusUrl: localVideoStatusUrl(localJob.id),
        artifact: responseArtifact(kind, prompt, undefined, url || undefined),
        message: url ? "Video generated." : "Video render queued.",
      })
    } catch (error) {
      updateAIJob(localJob.id, {
        status: "failed",
        error: error instanceof Error ? error.message : String(error),
      })
      const previewUrl = videoFallbackPreviewUrl(prompt)
      incrementUsage(entitlement.userId, entitlement.plan, "video")
      return Response.json({
        ok: true,
        kind,
        engine: publicEngineForProvider("demo-fallback", kind).title,
        fallbackUsed: true,
        status: "storyboard-ready",
        fallback: true,
        url: previewUrl,
        videoUrl: previewUrl,
        posterUrl: previewUrl,
        previewUrl: previewUrl,
        jobId: localJob.id,
        artifact: responseArtifact(kind, prompt, undefined, previewUrl),
        message: "Demo video storyboard ready. Live video rendering will work after server provider keys are configured.",
        publicError: publicErrorMessage(error),
      })
    }
  }

  const fallbackCode = kind === "code" ? codeArtifact(prompt) : websiteArtifact(prompt, kind)
  try {
    const task = kind === "code" ? "code" : "project"
    const result = await routeAI(
      applyFreeModeRequest({
        prompt: textPrompt(kind, prompt),
        task,
        provider: requestedProvider,
        userEmail: entitlement.userId,
        userId: entitlement.userId,
        plan: entitlement.plan,
        signal: request.signal,
        metadata: { requestedProvider },
      }),
    )
    const code = result.success && typeof result.output === "string" && result.output.trim() ? result.output : fallbackCode
    const fallback = !result.success
    return Response.json({
      ok: true,
      kind,
      engine: publicEngineForProvider(fallback ? "demo-fallback" : result.provider, kind).title,
      status: fallback ? "demo-ready" : "ready",
      code,
      html: kind === "code" ? undefined : code,
      fallback,
      fallbackUsed: fallback || result.fallbackUsed,
      artifact: responseArtifact(kind, prompt, code),
      message: fallback ? "Demo artifact ready. Live generation is being prepared on the server." : "Artifact generated.",
      publicError: fallback ? publicErrorMessage(result.error) : undefined,
    })
  } catch (error) {
    return Response.json({
      ok: true,
      kind,
      engine: publicEngineForProvider("demo-fallback", kind).title,
      status: "demo-ready",
      code: fallbackCode,
      html: kind === "code" ? undefined : fallbackCode,
      fallback: true,
      fallbackUsed: true,
      artifact: responseArtifact(kind, prompt, fallbackCode),
      message: "Demo artifact ready. Live generation is being prepared on the server.",
      publicError: publicErrorMessage(error),
    })
  }
}

export const runtime = "nodejs"
export const dynamic = "force-dynamic"
export const maxDuration = 300

export async function POST(request: Request) {
  return handleGenerateRequest(request)
}

export async function GET() {
  return Response.json({
    ok: true,
    product: "MALIK AI",
    route: "/api/generate",
    method: "POST",
    runtime,
    supportedKinds: Array.from(SUPPORTED_KINDS),
  })
}

export async function OPTIONS() {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
    },
  })
}
