export type RouterCatalogProvider = "xkiro" | "llm7" | "nara"
export type RouterCatalogMode = "text" | "image" | "video"
export type RouterCatalogAccess = "free" | "catalog"
export type RouterCatalogBrand = "mistral" | "minimax" | "qwen" | "sensenova" | "deepseek" | "zai" | "anthropic" | "google" | "openai" | "xai" | "kimi" | "meta" | "xiaomi" | "kling" | "bytedance" | "nvidia" | "nara" | "router"

export type RouterCatalogEntry = {
  provider: RouterCatalogProvider
  providerModel: string
  label: string
  mode: RouterCatalogMode
  access: RouterCatalogAccess
  brand: RouterCatalogBrand
  autoEligible: boolean
}

// Live catalogue snapshot verified from the user's three connected routers on 2026-09-20.
// "catalog" means the route exists in that provider catalogue but is not claimed to be free.
// MalikLLM MAX uses only autoEligible routes, so catalog/PAYG entries can never spend money automatically.
export const ROUTER_CATALOG = [
  { provider: "xkiro", providerModel: "mistralai/mistral-small-2603", label: "Mistral Small 4", mode: "text", access: "free", brand: "mistral", autoEligible: true },
  { provider: "xkiro", providerModel: "minimax/minimax-m3:free", label: "MiniMax M3 (Free)", mode: "text", access: "free", brand: "minimax", autoEligible: true },
  { provider: "xkiro", providerModel: "minimax/minimax-m2.5:free", label: "MiniMax M2.5 (Free)", mode: "text", access: "free", brand: "minimax", autoEligible: true },
  { provider: "xkiro", providerModel: "mistralai/mistral-large-2512", label: "Mistral Large 3", mode: "text", access: "free", brand: "mistral", autoEligible: true },
  { provider: "xkiro", providerModel: "minimax/minimax-m2:free", label: "MiniMax M2 (Free)", mode: "text", access: "free", brand: "minimax", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.8-omni-flash:free", label: "Qwen3.8 Omni Flash (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.5-omni-plus:free", label: "Qwen3.5 Omni Plus (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "mistralai/ministral-3b", label: "Ministral 3 3B", mode: "text", access: "free", brand: "mistral", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3-max:free", label: "Qwen3 Max (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "minimax/minimax-m2.7:free", label: "MiniMax M2.7 (Free)", mode: "text", access: "free", brand: "minimax", autoEligible: true },
  { provider: "xkiro", providerModel: "minimax/minimax-m2.5-highspeed:free", label: "MiniMax M2.5 Highspeed (Free)", mode: "text", access: "free", brand: "minimax", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen-plus-2025-07-28:free", label: "Qwen Plus 0728 (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3-omni-flash:free", label: "Qwen3 Omni Flash (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "mistralai/mistral-medium-3.5", label: "Mistral Medium 3.5", mode: "text", access: "free", brand: "mistral", autoEligible: true },
  { provider: "xkiro", providerModel: "minimax/minimax-m2.7-highspeed:free", label: "MiniMax M2.7 Highspeed (Free)", mode: "text", access: "free", brand: "minimax", autoEligible: true },
  { provider: "xkiro", providerModel: "mistralai/codestral-2508", label: "Codestral", mode: "text", access: "free", brand: "mistral", autoEligible: true },
  { provider: "xkiro", providerModel: "minimax/minimax-m2.1:free", label: "MiniMax M2.1 (Free)", mode: "text", access: "free", brand: "minimax", autoEligible: true },
  { provider: "xkiro", providerModel: "minimax/minimax-m2.1-highspeed:free", label: "MiniMax M2.1 Highspeed (Free)", mode: "text", access: "free", brand: "minimax", autoEligible: true },
  { provider: "xkiro", providerModel: "mistralai/devstral-medium", label: "Devstral 2", mode: "text", access: "free", brand: "mistral", autoEligible: true },
  { provider: "xkiro", providerModel: "mistralai/ministral-14b", label: "Ministral 3 14B", mode: "text", access: "free", brand: "mistral", autoEligible: true },
  { provider: "xkiro", providerModel: "mistralai/ministral-8b", label: "Ministral 3 8B", mode: "text", access: "free", brand: "mistral", autoEligible: true },
  { provider: "xkiro", providerModel: "sensenova/sensenova-6.8-flash-lite", label: "SenseNova 6.8 Flash-Lite", mode: "text", access: "free", brand: "sensenova", autoEligible: true },
  { provider: "xkiro", providerModel: "sensenova/sensenova-6.7-flash-lite", label: "SenseNova 6.7 Flash-Lite", mode: "text", access: "free", brand: "sensenova", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.8-max:free", label: "Qwen3.8 Max (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.7-plus:free", label: "Qwen3.7 Plus (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.7-flash:free", label: "Qwen3.7 Flash (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.6-plus:free", label: "Qwen3.6 Plus (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.6-max-preview:free", label: "Qwen3.6 Max Preview (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.7-max:free", label: "Qwen3.7 Max (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.6-27b:free", label: "Qwen3.6 27B (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.6-35b-a3b:free", label: "Qwen3.6 35B A3B (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.5-flash:free", label: "Qwen3.5 Flash (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.5-plus:free", label: "Qwen3.5 Plus (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3-coder-plus:free", label: "Qwen3 Coder Plus (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3-vl-plus:free", label: "Qwen3 VL Plus (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.5-397b-a17b:free", label: "Qwen3.5 397B A17B (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "qwen/qwen3.5-omni-flash:free", label: "Qwen3.5 Omni Flash (Free)", mode: "text", access: "free", brand: "qwen", autoEligible: true },
  { provider: "xkiro", providerModel: "sensenova/sensenova-u1.5-lite", label: "SenseNova U1.5 Lite", mode: "image", access: "free", brand: "sensenova", autoEligible: false },

  { provider: "llm7", providerModel: "DeepSeek-V4-Flash-0731", label: "DeepSeek-V4-Flash-0731", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "llm7", providerModel: "DeepSeek-V4.1-Flash", label: "DeepSeek-V4.1-Flash", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "llm7", providerModel: "GLM-5.3-Flash", label: "GLM-5.3-Flash", mode: "text", access: "catalog", brand: "zai", autoEligible: false },
  { provider: "llm7", providerModel: "Inkling", label: "Inkling", mode: "text", access: "catalog", brand: "router", autoEligible: false },
  { provider: "llm7", providerModel: "Inkling-Small", label: "Inkling-Small", mode: "text", access: "catalog", brand: "router", autoEligible: false },
  { provider: "llm7", providerModel: "L3-8B-Lunaris-v1-Turbo", label: "L3-8B-Lunaris-v1-Turbo", mode: "text", access: "catalog", brand: "router", autoEligible: false },
  { provider: "llm7", providerModel: "XiaomiMiMo/MiMo-V2.5", label: "XiaomiMiMo/MiMo-V2.5", mode: "text", access: "catalog", brand: "xiaomi", autoEligible: false },
  { provider: "llm7", providerModel: "XiaomiMiMo/MiMo-V2.5-Pro", label: "XiaomiMiMo/MiMo-V2.5-Pro", mode: "text", access: "catalog", brand: "xiaomi", autoEligible: false },
  { provider: "llm7", providerModel: "chroma-v.46-flash", label: "chroma-v.46-flash", mode: "image", access: "catalog", brand: "router", autoEligible: false },
  { provider: "llm7", providerModel: "claude-fable-5", label: "claude-fable-5", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "llm7", providerModel: "claude-fable-5-1", label: "claude-fable-5-1", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "llm7", providerModel: "claude-opus-4-8", label: "claude-opus-4-8", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "llm7", providerModel: "claude-opus-5", label: "claude-opus-5", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "llm7", providerModel: "claude-sonnet-4-6", label: "claude-sonnet-4-6", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "llm7", providerModel: "claude-sonnet-5", label: "claude-sonnet-5", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "llm7", providerModel: "codestral-latest", label: "codestral-latest", mode: "text", access: "catalog", brand: "mistral", autoEligible: false },
  { provider: "llm7", providerModel: "dark-beast-krea2", label: "dark-beast-krea2", mode: "image", access: "catalog", brand: "router", autoEligible: false },
  { provider: "llm7", providerModel: "deepseek-v4-flash:0731", label: "deepseek-v4-flash:0731", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "llm7", providerModel: "deepseek-v4-flash_0731", label: "deepseek-v4-flash_0731", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "llm7", providerModel: "deepseek-v4-pro", label: "deepseek-v4-pro", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "llm7", providerModel: "gemini-3-flash", label: "gemini-3-flash", mode: "text", access: "catalog", brand: "google", autoEligible: false },
  { provider: "llm7", providerModel: "gemini-3.1-flash-lite", label: "gemini-3.1-flash-lite", mode: "text", access: "catalog", brand: "google", autoEligible: false },
  { provider: "llm7", providerModel: "gemini-3.7-flash", label: "gemini-3.7-flash", mode: "text", access: "catalog", brand: "google", autoEligible: false },
  { provider: "llm7", providerModel: "gemini-3.8-flash-high", label: "gemini-3.8-flash-high", mode: "text", access: "catalog", brand: "google", autoEligible: false },
  { provider: "llm7", providerModel: "gemini-omni-flash", label: "gemini-omni-flash", mode: "text", access: "catalog", brand: "google", autoEligible: false },
  { provider: "llm7", providerModel: "gemma4:31b", label: "gemma4:31b", mode: "text", access: "catalog", brand: "google", autoEligible: false },
  { provider: "llm7", providerModel: "glm-5.3", label: "glm-5.3", mode: "text", access: "catalog", brand: "zai", autoEligible: false },
  { provider: "llm7", providerModel: "gpt-5.5", label: "gpt-5.5", mode: "text", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "llm7", providerModel: "gpt-5.6-luna", label: "gpt-5.6-luna", mode: "text", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "llm7", providerModel: "gpt-5.6-sol", label: "gpt-5.6-sol", mode: "text", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "llm7", providerModel: "gpt-5.6-terra", label: "gpt-5.6-terra", mode: "text", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "llm7", providerModel: "gpt-6-astra", label: "gpt-6-astra", mode: "text", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "llm7", providerModel: "gpt-image-2", label: "gpt-image-2", mode: "image", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "llm7", providerModel: "gpt-image-2.5", label: "gpt-image-2.5", mode: "image", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "llm7", providerModel: "grok-4.5", label: "grok-4.5", mode: "text", access: "catalog", brand: "xai", autoEligible: false },
  { provider: "llm7", providerModel: "grok-4.6", label: "grok-4.6", mode: "text", access: "catalog", brand: "xai", autoEligible: false },
  { provider: "llm7", providerModel: "kimi-k3", label: "kimi-k3", mode: "text", access: "catalog", brand: "kimi", autoEligible: false },
  { provider: "llm7", providerModel: "kling-v3.0-pro", label: "kling-v3.0-pro", mode: "video", access: "catalog", brand: "kling", autoEligible: false },
  { provider: "llm7", providerModel: "kling-v3.0-turbo", label: "kling-v3.0-turbo", mode: "video", access: "catalog", brand: "kling", autoEligible: false },
  { provider: "llm7", providerModel: "llama-4-maverick", label: "llama-4-maverick", mode: "text", access: "catalog", brand: "meta", autoEligible: false },
  { provider: "llm7", providerModel: "minimax-m2.7", label: "minimax-m2.7", mode: "text", access: "catalog", brand: "minimax", autoEligible: false },
  { provider: "llm7", providerModel: "mistral-Nemo-Instruct-2407", label: "mistral-Nemo-Instruct-2407", mode: "text", access: "catalog", brand: "mistral", autoEligible: false },
  { provider: "llm7", providerModel: "mistral-Small-24B-Instruct-2501", label: "mistral-Small-24B-Instruct-2501", mode: "text", access: "catalog", brand: "mistral", autoEligible: false },
  { provider: "llm7", providerModel: "seed-2.0-mini", label: "seed-2.0-mini", mode: "text", access: "catalog", brand: "bytedance", autoEligible: false },
  { provider: "llm7", providerModel: "seedance-2.0", label: "seedance-2.0", mode: "video", access: "catalog", brand: "bytedance", autoEligible: false },
  { provider: "llm7", providerModel: "seedance-2.0-fast", label: "seedance-2.0-fast", mode: "video", access: "catalog", brand: "bytedance", autoEligible: false },
  { provider: "llm7", providerModel: "seedance-2.0-mini", label: "seedance-2.0-mini", mode: "video", access: "catalog", brand: "bytedance", autoEligible: false },

  { provider: "nara", providerModel: "agnes-2.5-flash", label: "Agnes 2.5 Flash", mode: "text", access: "free", brand: "nara", autoEligible: true },
  { provider: "nara", providerModel: "agnes-3-flash", label: "Agnes 3 Flash", mode: "text", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "agnes-video-v2.0", label: "Agnes Video 2.0", mode: "video", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "claude-fable-5", label: "Claude Fable 5", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "nara", providerModel: "claude-fable-5.1", label: "Claude Fable 5.1", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "nara", providerModel: "claude-opus-4.7", label: "Claude Opus 4.7", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "nara", providerModel: "claude-opus-4.8", label: "Claude Opus 4.8", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "nara", providerModel: "claude-opus-5", label: "Claude Opus 5", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "nara", providerModel: "claude-sonnet-5", label: "Claude Sonnet 5", mode: "text", access: "catalog", brand: "anthropic", autoEligible: false },
  { provider: "nara", providerModel: "deepseek-v4-flash-alibaba", label: "Deepseek v4 Flash 0731 Alibaba", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "nara", providerModel: "deepseek-v4-flash-vision-exp", label: "DeepSeek V4 Flash Vision (exp)", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "nara", providerModel: "deepseek-v4-pro-alibaba", label: "Deepseek v4 Pro 0813 Alibaba", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "nara", providerModel: "deepseek-v4.1-flash", label: "Deepseek v4.1 Flash", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "nara", providerModel: "deepseek-v4.1-flash-promo", label: "DeepSeek v4.1 Flash Promo", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "nara", providerModel: "gemini-3.1-pro-high", label: "Gemini 3.1 Pro High", mode: "text", access: "catalog", brand: "google", autoEligible: false },
  { provider: "nara", providerModel: "gemini-3.8-flash-high", label: "Gemini 3.8 Flash High", mode: "text", access: "catalog", brand: "google", autoEligible: false },
  { provider: "nara", providerModel: "glm-5.2", label: "GLM 5.2", mode: "text", access: "catalog", brand: "zai", autoEligible: false },
  { provider: "nara", providerModel: "glm-5.3", label: "GLM 5.3", mode: "text", access: "catalog", brand: "zai", autoEligible: false },
  { provider: "nara", providerModel: "glm-5.3-flash", label: "GLM 5.3 Flash", mode: "text", access: "catalog", brand: "zai", autoEligible: false },
  { provider: "nara", providerModel: "gpt-5.6-luna", label: "GPT 5.6 Luna", mode: "text", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "nara", providerModel: "gpt-5.6-sol", label: "GPT 5.6 Sol", mode: "text", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "nara", providerModel: "gpt-5.6-terra", label: "GPT 5.6 Terra", mode: "text", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "nara", providerModel: "gpt-6-astra", label: "GPT 6 Astra", mode: "text", access: "catalog", brand: "openai", autoEligible: false },
  { provider: "nara", providerModel: "kimi-k2.7-code", label: "Kimi K2.7-code", mode: "text", access: "catalog", brand: "kimi", autoEligible: false },
  { provider: "nara", providerModel: "kimi-k3", label: "Kimi K3", mode: "text", access: "catalog", brand: "kimi", autoEligible: false },
  { provider: "nara", providerModel: "laguna-s-2.1", label: "Laguna S 2.1", mode: "text", access: "free", brand: "nara", autoEligible: true },
  { provider: "nara", providerModel: "ling-3.0-flash-fin-free", label: "Ling 3.0 Flash Fin Free", mode: "text", access: "free", brand: "nara", autoEligible: true },
  { provider: "nara", providerModel: "ling-3.0-flash-sante-free", label: "Ling 3.0 Flash Sante Free", mode: "text", access: "free", brand: "nara", autoEligible: true },
  { provider: "nara", providerModel: "ling-3.0-flash-vl-free", label: "Ling 3.0 Flash VL", mode: "text", access: "free", brand: "nara", autoEligible: true },
  { provider: "nara", providerModel: "mimo-v2.5", label: "MiMo v2.5", mode: "text", access: "catalog", brand: "xiaomi", autoEligible: false },
  { provider: "nara", providerModel: "mimo-v2.5-free", label: "Mimo v2.5 Free", mode: "text", access: "free", brand: "xiaomi", autoEligible: true },
  { provider: "nara", providerModel: "minimax-m3", label: "MiniMax M3", mode: "text", access: "catalog", brand: "minimax", autoEligible: false },
  { provider: "nara", providerModel: "muse-spark-1.2", label: "Muse Spark 1.2", mode: "text", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "muse-spark-1.2-contributor", label: "Muse Spark 1.2 Contributor", mode: "text", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "muse-spark-1.3", label: "Muse Spark 1.3", mode: "text", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "muse-spark-1.3-contributor", label: "Muse Spark 1.3 Contributor", mode: "text", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "muse-spark-1.3-contributor-free", label: "Muse Spark 1.3 Contributor Free", mode: "text", access: "free", brand: "nara", autoEligible: true },
  { provider: "nara", providerModel: "nemotron-3-super-free", label: "Nemotron 3 Super Free", mode: "text", access: "free", brand: "nvidia", autoEligible: true },
  { provider: "nara", providerModel: "nemotron-3-ultra-free", label: "Nemotron 3 Ultra Free", mode: "text", access: "free", brand: "nvidia", autoEligible: true },
  { provider: "nara", providerModel: "nemotron-3.5-lightning-free", label: "Nemotron 3.5 Lightning", mode: "text", access: "free", brand: "nvidia", autoEligible: true },
  { provider: "nara", providerModel: "nex-n2.5-pro", label: "Nex n2.5 Pro", mode: "text", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "qwen3.8-27b", label: "Qwen 3.8 27B", mode: "text", access: "catalog", brand: "qwen", autoEligible: false },
  { provider: "nara", providerModel: "qwen3.8-flash", label: "Qwen 3.8 Flash", mode: "text", access: "catalog", brand: "qwen", autoEligible: false },
  { provider: "nara", providerModel: "qwen3.8-max", label: "Qwen3.8-Max", mode: "text", access: "catalog", brand: "qwen", autoEligible: false },
  { provider: "nara", providerModel: "qwen3.8-max-alibaba", label: "Qwen3.8-Max Alibaba", mode: "text", access: "catalog", brand: "qwen", autoEligible: false },
  { provider: "nara", providerModel: "stepfun-3.7-flash", label: "Stepfun 3.7 Flash", mode: "text", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "deepseek-v4-flash", label: "DeepSeek v4 Flash 0731", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "nara", providerModel: "deepseek-v4-pro", label: "DeepSeek v4 Pro 0813", mode: "text", access: "catalog", brand: "deepseek", autoEligible: false },
  { provider: "nara", providerModel: "mimo-v2.5-pro", label: "MiMo v2.5 Pro", mode: "text", access: "catalog", brand: "xiaomi", autoEligible: false },

  { provider: "nara", providerModel: "agnes-image-2.0-flash", label: "Agnes Image 2.0 Flash", mode: "image", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "agnes-image-2.1-flash", label: "Agnes Image 2.1 Flash", mode: "image", access: "catalog", brand: "nara", autoEligible: false },
  { provider: "nara", providerModel: "grok-imagine", label: "Grok Imagine", mode: "image", access: "catalog", brand: "xai", autoEligible: false },
  { provider: "nara", providerModel: "nano-banana-pro", label: "Nano Banana Pro", mode: "image", access: "catalog", brand: "google", autoEligible: false },
] as const satisfies readonly RouterCatalogEntry[]

export const ROUTER_TEXT_CATALOG = ROUTER_CATALOG.filter((entry) => entry.mode === "text")
export const ROUTER_IMAGE_CATALOG = ROUTER_CATALOG.filter((entry) => entry.mode === "image")
export const ROUTER_VIDEO_CATALOG = ROUTER_CATALOG.filter((entry) => entry.mode === "video")
export const ROUTER_AUTO_TEXT_CATALOG = ROUTER_TEXT_CATALOG.filter((entry) => entry.autoEligible)

export const ROUTER_CATALOG_COUNTS = {
  total: ROUTER_CATALOG.length,
  text: ROUTER_TEXT_CATALOG.length,
  image: ROUTER_IMAGE_CATALOG.length,
  video: ROUTER_VIDEO_CATALOG.length,
} as const
